import Head from "next/head";
import styled from "styled-components";

const Container = styled.div`
  width: 100%;
  height: calc(100vh - 60px);
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Title>Home</Title>
        </Container>
      </main>

      <footer>
        {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
      </footer>
    </div>
  );
}
