import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";
import Teste from "../assets/YT_branco.png";
//import { useAuth } from "../Context/auth";

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.colors.primary};
`;

export default function Home() {
  
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Image src={Teste} alt="Vercel Logo" width={100} height={30} />
        <Title>Teste</Title>
        <h1>Hello World</h1>
      </main>

      <footer>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </footer>
    </div>
  );
}
